
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Check

on:
  push:
  pull_request:
  schedule:
    # once a week (every Monday at 3AM)
    - cron: "0 3 * * 1"

jobs:

  File_check:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/head/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Check systemd States
      run: ./systemd_status_check.rb
